jwt:
  secret:
    key: 7ZWt7ZW0OTntmZTsnbTtjIXtlZzqta3snYTrhIjrqLjshLjqs4TroZzrgpjslYTqsIDsnpDtm4zrpa3tlZzqsJzrsJzsnpDrpbzrp4zrk6TslrTqsIDsnpA=
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://hanghae66.c0q7tdzdm5qz.ap-northeast-2.rds.amazonaws.com:3306/hanghae66
    username: hh66
    password: leehyeongyu
cloud:
  aws:
    credentials:
      accessKey: AKIA6BJV2PX4CLIVW54K
      secretKey: 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
    s3:
      bucket: myapoorpoor
    stack:
      auto-: 'false'
    region:
      static: ap-northeast-2