jwt:
  secret:
    key: 7ZWt7ZW0OTntmZTsnbTtjIXtlZzqta3snYTrhIjrqLjshLjqs4TroZzrgpjslYTqsIDsnpDtm4zrpa3tlZzqsJzrsJzsnpDrpbzrp4zrk6TslrTqsIDsnpA=
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://hanghae66.c0q7tdzdm5qz.ap-northeast-2.rds.amazonaws.com:3306/hanghae66
    username: hh66
    password: leehyeongyu
cloud:
  aws:
    credentials:
      accessKey: AKIAS3OJXK222RFP5LKI
      secretKey: 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
    s3:
      bucket: apoorapoors3
    stack:
      auto-: 'false'
    region:
      static: ap-northeast-2