jwt:
  secret:
    key: ENC(PpydS4hJ1qqWdJwmVD5DDu/XApNXPDxcVUgeGWUVpZHWBPlB1OxVLwytCXMwnc+77Q7PlbrcWuK+Ui6cQRzyDuM3D1tvOI2QSvb6CQ8YFiarriwV/Rb7xr5DLeLUUjSRLEt5Xbzi1jue8opYU67TMi5llFS7bIuw/iEhMamXWDGxD2mZsVJjwA==)
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(yLYj7DetbjoqMe3nFqiDo20xwNLZ4IZyyI7VUoVLi8fqX2CFCSMV/sFIMAYiFF2/yoi5ZsFTq62i19RtkS5FWWTFupJ3ejWdNhTcnUHR/NdNjzcFgM59RQhJQdnqpxUM)
    username: ENC(QT2XQXHR8ApzWiW3ePytmw==)
    password: ENC(HDhr3OhGNW8Y4a7T44qMLsIEUOZ4jG0H)
cloud:
  aws:
    credentials:
      accessKey: ENC(/G5NX6F1cM/T6vucF9/4bkL+LEpbG+Ot5g/nV3SBTq0=)
      secretKey: ENC(TBNSKPMj5mhJoeboNn2md983ROiPJEwcVdMuP1Bx6lKBjnux+AXdx5xAXKsdVD2jka33y0h1B78=)
    s3:
      bucket: ENC(vtQ4dAt19k8jsRyR3JIefSFn1zBWBbPN)
    stack:
      auto-: 'false'
    region:
      static: ap-northeast-2



