spring:
  config.activate.on-profile: default
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

