spring:
  config.activate.on-profile: default
  config:
    import: application-secret.yml
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  data:
    redis:
      host: 127.0.0.1
      port: 6379

