spring:
  profiles:
    group:
      "local" : "local, jwt, oauth"
    active : local

---
spring:
  config:
    activate:
      on-profile: "local"

  h2:
    console:
      enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://hanghae66.c0q7tdzdm5qz.ap-northeast-2.rds.amazonaws.com:3306/hanghae66
    username: hh66
    password: leehyeongyu

#  jpa:
#    show-sql: true
#    database-platform: org.hibernate.dialect.H2Dialect
#    properties:
#      hibernate:
#        format_sql: true
#        show_sql: true
#
#    hibernate:
#      ddl-auto: create
  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

#cloud:
#  aws:
#    credentials:
#      accessKey: AKIA6BJV2PX4JZTXKNLG
#      secretKey: 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
#    s3:
#
#    stack:
#      auto-: 'false'
#    region:
#      static: ap-northeast-2

