# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle
name: Java CI with Gradle
on:
  push:
    branches: [ "release" ]
env:
  PROJECT_NAME: apoorapoor
  BUCKET_NAME: 4-cicd
  CODE_DEPLOY_APP_NAME: my-codedeploy-app
  DEPLOYMENT_GROUP_NAME: my-codedeploy-deployment-group

jobs:
  build:
    # 실행 환경 지정
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Add permission
        run: chmod +x ./gradlew
        shell: bash
      - name: Set YML
        run: |
          echo ${{secrets.APPLICATION_SECRET_KEY}} | base64 --decode >> ./src/main/resources/application-secret.yml
      # Build
      - name: Build with Gradle
        run: |
          ./gradlew build
          ./gradlew bootJar
        shell: bash
      - name: Make Zip File
        run: zip -r ./$PROJECT_NAME.zip .
        shell: bash
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$PROJECT_NAME.zip s3://$BUCKET_NAME/$PROJECT_NAME.zip
      # Deploy 설정
      - name: Code Deploy
        run: aws deploy create-deployment --application-name $CODE_DEPLOY_APP_NAME --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name $DEPLOYMENT_GROUP_NAME --s3-location bucket=$BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME.zip
